### ISSUE TITLE
Hardcoded default Python path

### ISSUE THREAD

**Issue by vanyasem** [ubports/net-cpp#2]
The path to Python2 `/usr/bin/python` is hardcoded in `tests/httpbin.h.in`

However, `/usr/bin/python` defaults to Python3 on Arch GNU/Linux, and thus the build fails.

**Comment by UniversalSuperBox** [comment]
Fixed by https://gitlab.com/ubports/core/lib-cpp/net-cpp/-/commit/e028baabc3627d5d13b9a9db2d096990ce7b7459
