### ISSUE TITLE
Compressed httpbin webserver fails to run with new Flask

### ISSUE THREAD

**Issue by vanyasem** [ubports/net-cpp#3]
There is a compressed python-based webserver in the repo that's used to run tests (`tests/httpbin.tar.bz2`).

However, with the newest changes in Flask packages, the current flask-script import fails. It's impossible to just patch the required import, as it's an archive, so I had to use nasty binary patching.

In `run.py` inside the archive: `from flask.ext.script import Manager, Command` should be replaced by `from flask_script import Manager, Command`

**Comment by UniversalSuperBox** [comment]
Fixed by https://gitlab.com/ubports/core/lib-cpp/net-cpp/-/commit/e028baabc3627d5d13b9a9db2d096990ce7b7459
